# Generated by Django 4.2.3 on 2023-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
